// Image paths for the application
export const IMAGES = {
    // Hero images for landing page
    hero: {
        homeButton: '0-homebutton-nest-haus',
        mobile: '8-NEST-Haus-Innenperspektive-Schwarze-Steinplatten-mobile',
        nestHaus1: '1-NEST-Haus-Berg-Vision-AUSTRIA-SWISS-Holzlattung-Laerche',
        nestHaus2: '2-NEST-Haus-7-Module-Ansicht-Weisse-Fassadenplatten',
        nestHaus3: '3-NEST-Haus-3-Gebaeude-Vogelperspektive-Holzlattung-Laerche',
        nestHaus4: '4-NEST-Haus-2-Gebaeude-Schnee-Stirnseite-Schwarze-Trapezblech-Fassade',
        nestHaus5: '5-NEST-Haus-6-Module-Wald-Ansicht-Schwarze-Fassadenplatten',
        nestHaus6: '6-NEST-Haus-4-Module-Ansicht-Meer-Mediteran-Stirnseite-Holzlattung-Laerche',
        nestHaus7: '7-NEST-Haus-Innenperspektive-Kalkstein-Holz-Verglasung-Stirnseite',
        nestHaus8: '8-NEST-Haus-Innenperspektive-Schwarze-Steinplatten'
        }
    },

    // Gallery images
    gallery: {
        house1: 'house-1',
        house2: 'house-2',
        house3: 'house-3',
        house4: 'house-4',
        house5: 'house-5'
        },

    // Function/Process images
    function: {
        nest-haus-ablauf-prozess-planung: '39-NEST-Haus-Ablauf-Prozess-Planung',
        nest-haus-erweiterung-modulbau-vergro_ern-leichtbau-modul-flexibel: '38-NEST-Haus-erweiterung-Modulbau-vergrößern-Leichtbau-Modul-flexibel',
        nest-haus-grundstueck-check-einreichung-planung: '25-NEST-Haus-Grundstueck-Check-Einreichung-Planung',
        nest-haus-innenausbau-fenster-tueren-schema-konzept-mobil: '16-NEST-Haus-Innenausbau-Fenster-Tueren-Schema-Konzept-Mobil',
        nest-haus-leitungen-anschluss-kanal-wasser-strom: '27-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom',
        nest-haus-leitungen-anschluss-kanal-wasser-strom-modul: '28-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom-Modul',
        nest-haus-leitungen-anschluss-kanal-wasser-strom-module-zusammenschluss: '29-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom-Module-Zusammenschluss',
        nest-haus-materialien-schema-konzept-holz-mobil: '14-NEST-Haus-Materialien-Schema-Konzept-Holz-Mobil',
        nest-haus-modul-ansicht-modul-holz-schema-konzept: '21-NEST-Haus-Modul-Ansicht-Modul-Holz-Schema-Konzept',
        nest-haus-modul-ansicht-modul-holz-schema-konzept-liniengrafik: '22-NEST-Haus-Modul-Ansicht-Modul-Holz-Schema-Konzept-Liniengrafik',
        nest-haus-modul-ansicht-seite-holz-schema-konzept: '23-NEST-Haus-Modul-Ansicht-Seite-Holz-Schema-Konzept',
        nest-haus-modul-ansicht-seite-holz-schema-konzept-liniengrafik: '24-NEST-Haus-Modul-Ansicht-Seite-Holz-Schema-Konzept-Liniengrafik',
        nest-haus-modul-ansicht-stirnseite-holz-schema-konzept: '20-NEST-Haus-Modul-Ansicht-Stirnseite-Holz-Schema-Konzept',
        nest-haus-modul-schema-konzept-explosionszeichnung-abschluss-animation: '17-NEST-Haus-Modul-Schema-Konzept-Explosionszeichnung-abschluss-animation',
        nest-haus-modul-schema-konzept-explosionszeichnung-intro-animation: '12-NEST-Haus-Modul-Schema-Konzept-Explosionszeichnung-intro-animation',
        nest-haus-planung-elektrik-sanita_r-einbau-geba_udetechnik-hkls-modul: '35-NEST-Haus-Planung-Elektrik-Sanitär-Einbau-Gebäudetechnik-HKLS-Modul',
        nest-haus-planung-innenausbau-fenster-tueren-einbau-positionierung-abschlussmodul-liniengrafik: '32-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung-Abschlussmodul-Liniengrafik',
        nest-haus-planung-innenausbau-fenster-tueren-einbau-positionierung-mittelmodul-liniengrafik: '31-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung-Mittelmodul-Liniengrafik',
        nest-haus-planung-innenausbau-fenster-tueren-einbau-positionierung-modul: '30-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung-Modul',
        nest-haus-planung-innenausbau-fenster-tueren-stirnseite: '34-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Stirnseite',
        nest-haus-planung-innenausbau-mo_blierung-hausbau-flexibel: '33-NEST-Haus-Planung-Innenausbau-möblierung-hausbau-flexibel',
        nest-haus-planung-innenausbau-moeblierung-hausbau-flexibel: '33-NEST-Haus-Planung-Innenausbau-moeblierung-hausbau-flexibel',
        nest-haus-planung-innenausbau-zeichnen-grundriss: '26-NEST-Haus-Planung-Innenausbau-Zeichnen-Grundriss',
        nest-haus-planung-innenausbau-zwischendecke-leichtbau-modul: '36-NEST-Haus-Planung-Innenausbau-Zwischendecke-Leichtbau-Modul',
        nest-haus-planung-innenausbau-zwischendecke-leichtbau-modul-liniengrafik: '37-NEST-Haus-Planung-Innenausbau-Zwischendecke-Leichtbau-Modul-Liniengrafik',
        nest-haus-system-hausbau-modulbau-dein-part-innenausbau-mo_blierung-personlisierung: '15-NEST-Haus-System-Hausbau-Modulbau-dein-part-Innenausbau-möblierung-personlisierung',
        nest-haus-system-hausbau-modulbau-serienproduktion-modulbau-flexibel-holzbau-mobil: '13-NEST-Haus-System-Hausbau-Modulbau-Serienproduktion-Modulbau-flexibel-Holzbau-Mobil',
        nestHausAblaufPlanung: '39-NEST-Haus-Ablauf-Prozess-Planung',
        nestHausFensterTuerenAbschlussmodul: '32-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung-Abschlussmodul-Liniengrafik',
        nestHausFensterTuerenMittelmodul: '31-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung-Mittelmodul-Liniengrafik',
        nestHausFensterTuerenPosition: '30-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Einbau-Positionierung',
        nestHausFensterTuerenStirnseite: '34-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Stirnseite',
        nestHausFensterTuerenStirnseiteLinien: '35-NEST-Haus-Planung-Innenausbau-Fenster-Tueren-Stirnseite-Liniengrafik',
        nestHausFundamentPunktfundament: '38-NEST-Haus-Fundament-Punktfundament',
        nestHausFundamentStreifenfundament: '37-NEST-Haus-Fundament-Bestandsgebaeude-Keller-Streifenfundament',
        nestHausGrundrissSchema: '33-NEST-Haus-Planung-Innenausbau-moeblierung-hausbau-flexibel',
        nestHausGrundstueckCheck: '25-NEST-Haus-Grundstueck-Check-Einreichung-Planung',
        nestHausHandDrawing: '26-NEST-Haus-Planung-Innenausbau-Zeichnen-Grundriss',
        nestHausKonfigurator: '104-NEST-Haus-Konfigurator-75-Holzfassade-Ansicht',
        nestHausLeitungenAnschluss: '27-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom',
        nestHausLeitungenAnschlussModul: '28-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom-Modul',
        nestHausLeitungenZusammenschluss: '29-NEST-Haus-Leitungen-Anschluss-Kanal-Wasser-Strom-Module-Zusammenschluss',
        nestHausModulAnsicht: '20-NEST-Haus-Modul-Ansicht-Stirnseite-Holz-Schema-Konzept',
        nestHausModulKonzept: '21-NEST-Haus-Modul-Ansicht-Modul-Holz-Schema-Konzept',
        nestHausModulLiniengrafik: '22-NEST-Haus-Modul-Ansicht-Modul-Holz-Schema-Konzept-Liniengrafik',
        nestHausModulSchema: '12-NEST-Haus-Modul-Schema-Konzept-Explosionszeichnung',
        nestHausModulSeiteKonzept: '23-NEST-Haus-Modul-Ansicht-Seite-Holz-Schema-Konzept',
        nestHausModulSeiteLiniengrafik: '24-NEST-Haus-Modul-Ansicht-Seite-Holz-Schema-Konzept-Liniengrafik',
        nestHausPlattenFundament: '36-NEST-Haus-Fundament-Plattenfundament'
        },

    aboutus: {
        materialEiche: '132-NEST-Haus-Konfigurator-Materialien-Innenverkleidung-Holz-Steirische-Eiche',
        team: '999_TEAM',
        team2: '998_TEAM',
        team3: '998_TEAM'
        },

    // Configurator images
    configurations: {
        config_0: '0-homebutton-nest-haus',
        config_124: '124-NEST-Haus-Konfigurator-Fussboden-Naturstein-Granit-Dunkel',
        config_125: '125-NEST-Haus-Konfigurator-Fussboden-Naturstein-Kalkstein-Hell',
        config_126: '126-NEST-Haus-Konfigurator-Fussboden-Parkett-Eiche',
        config_127: '127-NEST-Haus-Konfigurator-Materialien-Fassade-Holzfassade-Laerche',
        config_128: '128-NEST-Haus-Konfigurator-Materialien-Fassade-Platten-Schwarz',
        config_129: '129-NEST-Haus-Konfigurator-Materialien-Fassade-Platten-Weiss',
        config_130: '130-NEST-Haus-Konfigurator-Materialien-Fassade-Trapezblech-Schwarz',
        config_131: '131-NEST-Haus-Konfigurator-Materialien-Innenverkleidung-Holz-Natur',
        config_132: '132-NEST-Haus-Konfigurator-Materialien-Innenverkleidung-Holz-Steirische-Eiche',
        config_133: '133-NEST-Haus-Konfigurator-Materialien-Innenverkleidung-Holz-Weiss-Gekalkt',
        config_134: '134-NEST-Haus-Konfigurator-Modul-Fassade-Holzfassade-Photovoltaik-PV-Panel',
        config_135: '135-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Photovoltaik-PV-Panel',
        config_136: '136-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Granit-7CCA8LGFbRra4Dxi2g',
        config_137: '137-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Kalkstein-D4RAtIS4jkTCwsIg',
        config_139: '139-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Granit-K5tyKMAs9CuqDWj1IQ',
        config_140: '140-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Kalkstein-TuZTdfJVyrLvbx9zZQ',
        config_143: '143-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Kalkstein-A7YVClW1EFmSveW4g',
        config_145: '145-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Granit-4avkt0wUVrMEmcNNQA',
        config_149: '149-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Kalkstein-bIjcHGm9URCiJSL9xQ',
        config_151: '151-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Photovoltaik-PV-Panel',
        config_152: '152-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Granit-SRHEgWGUTdYvRrUvSQ',
        config_154: '154-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Parkett-Eiche-DQ1MNqesVzd6QXl7kQ',
        config_155: '155-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Granit-zPnmHM9CUVGJytMvqg',
        config_157: '157-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Parkett-Eiche-FYaLla8TohuilLZwfA',
        config_158: '158-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Granit-NZzwxzad9QOUPfNG5A',
        config_159: '159-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Kalkstein-K2H9EaUx3lVrcSDqlQ',
        config_161: '161-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Photovoltaik-PV-Panel',
        config_163: '163-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Kalkstein-JAWdKUbrNHYZjb5sRw',
        config_164: '164-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Parkett-Eiche-v5mdhR6JMDOUi1O8A',
        config_165: '165-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Schiefer-G0EhTm2OkTBMy1tzMw',
        config_166: '166-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Kalkstein-LH5wYSXCtMh7NpsWw',
        config_167: '167-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Parkett-Eiche-b2ImmnG4DtzqGouuUA',
        config_168: '168-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Granit-6RWC5Nd6WCLYz4Q9g',
        config_171: '171-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Granit-1vXk9sWiIZyJBfWsZQ',
        config_173: '173-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Parkett-Eiche-0oaZMiP6zjwqOgp2w',
        config_174: '174-NEST-Haus-Fenster-Holz-Eiche-Holzfenster-Eichenfenster',
        config_175: '175-NEST-Haus-Fenster-Holz-Fichte-Holzfenster-Fichtenfenster',
        config_176: '176-NEST-Haus-Fenster-Aluminium-Fenster-Aluminiumfenster-Metallfenster',
        config_177: '177-NEST-Haus-Fenster-Kunststoff-PVC-Fenster-Weiss-Kunststofffenster-PVCFenster',
        config_46: '46-NEST-Haus-Materialien-Bauteilaufbau-Konstruktion-Brettschichtholz-BSH-Fichte',
        config_47: '47-NEST-Haus-Materialien-Bauteilaufbau-Konstruktion-Holzfaserplatte-Holzwolle-Holzfaserdaemmung-Isolierung',
        config_48: '48-NEST-Haus-PV-Phovtovoltaik-Solar-Panele-Fassade-Nachhaltig-Strom',
        config_49: '49-NEST-Haus-Materialien-Oberflaechen-Fussboden-Eichenholz-Parkett-Fischgraetparkett-Eiche-1xOtEfSHoFczo4w',
        config_50: '50-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Eichenholz-Interior-Eiche',
        config_51: '51-NEST-Haus-Materialien-Bauteilaufbau-Konstruktion-OSB-Oriented-Strand-Board-Recycling-Oekologisch',
        config_52: '52-NEST-Haus-Materialien-Oberflaechen-Fassade-Laerche-Bauholz-Lattung',
        config_53: '53-NEST-Haus-Materialien-Oberflaechen-Fassadenplatte-Schwarz',
        config_54: '54-NEST-Haus-Materialien-Oberflaechen-Fassadenplatte-Weiss',
        config_55: '55-NEST-Haus-Materialien-Oberflaechen-Fassade-Trapezblech-Blech-Schwarz',
        config_56: '56-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Kalkstein-Kanafar',
        config_57: '57-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Schiefer-Feinsteinzeug',
        config_58: '58-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Interior-Fichte-natur-hell',
        config_59: '59-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Interior-Kiefer-natur',
        config_60: '60-NEST-Haus-Partner-Kooperation-Technische-Universitaet-Graz-TU-Graz',
        config_61: '61-NEST-Haus-Partner-Kooperation-Engelsmann-Peters-Professor-TU-Graz-Stefan-Peters',
        config_62: '62-NEST-Haus-Partner-Kooperation-Technische-Universitaet-Graz-TU-Graz-IAM-Institut',
        config_63: '63-NEST-Haus-Partner-Kooperation-Technische-Universitaet-Graz-TU-Graz-Labor-Bauphysik',
        config_64: '64-NEST-Haus-Partner-Kooperation-Schwarz-Partner-Patentanwaelte',
        config_65: '65-NEST-Haus-Partner-Kooperation-Sobitsch-Zimmerer-Zimmerermeisterbetrieb-Holzbaumeister-Innenausbau',
        fenster_aluminium: '176-NEST-Haus-Fenster-Aluminium-Fenster-Aluminiumfenster-Metallfenster',
        fenster_holz_eiche: '174-NEST-Haus-Fenster-Holz-Eiche-Holzfenster-Eichenfenster',
        fenster_holz_fichte: '175-NEST-Haus-Fenster-Holz-Fichte-Holzfenster-Fichtenfenster',
        fenster_pvc: '177-NEST-Haus-Fenster-Kunststoff-PVC-Fenster-Weiß-Kunststofffenster-PVCFenster',
        holzlattung_eiche_kalkstein: '172-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Kalkstein',
        holzlattung_eiche_parkett: '173-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Parkett-Eiche',
        holzlattung_eiche_schiefer: '171-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Granit',
        holzlattung_holznatur_kalkstein: '166-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Kalkstein',
        holzlattung_holznatur_parkett: '167-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Parkett-Eiche',
        holzlattung_holznatur_schiefer: '165-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-Natur-Schiefer',
        holzlattung_holzweiss_kalkstein: '169-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Kalkstein',
        holzlattung_holzweiss_parkett: '170-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Parkett-Eiche',
        holzlattung_holzweiss_schiefer: '168-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Granit',
        holzlattung_interior: 'holzlattung_kalkstein',
        interiorDefault: '137-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Kalkstein',
        nest005_: '172-NEST-Haus-Konfigurator-Modul-Holzfassade-Steirische-Eiche-Kalkstein-Td5zuMOGyYY005K4sw',
        nest03_: '147-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Parkett-Eiche-nTEXR03NhrxPIgxA',
        nest115: '114-NEST-Haus-Konfigurator-115-Holzfassade-Ansicht',
        nest115_: '115-NEST-Haus-Konfigurator-115-Trapezblech-Schwarz-Ansicht',
        nest115_holzlattung: '114-NEST-Haus-Konfigurator-115-Holzfassade-Ansicht',
        nest115_plattenschwarz: '112-NEST-Haus-Konfigurator-115-Fassadenplatten-Schwarz-Ansicht',
        nest115_plattenweiss: '113-NEST-Haus-Konfigurator-115-Fassadenplatten-Weiss-Ansicht',
        nest115_trapezblech: '115-NEST-Haus-Konfigurator-115-Trapezblech-Schwarz-Ansicht',
        nest13_: '138-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Parkett-Eiche-rMZNHAWJp0h2N5X13Q',
        nest135: '118-NEST-Haus-Konfigurator-135-Holzfassade-Ansicht',
        nest135_: '119-NEST-Haus-Konfigurator-135-Trapezblech-Schwarz-Ansicht',
        nest135_holzlattung: '118-NEST-Haus-Konfigurator-135-Holzfassade-Ansicht',
        nest135_plattenschwarz: '116-NEST-Haus-Konfigurator-135-Fassadenplatten-Schwarz-Ansicht',
        nest135_plattenweiss: '117-NEST-Haus-Konfigurator-135-Fassadenplatten-Weiss-Ansicht',
        nest135_trapezblech: '119-NEST-Haus-Konfigurator-135-Trapezblech-Schwarz-Ansicht',
        nest155: '122-NEST-Haus-Konfigurator-155-Holzfassade-Ansicht',
        nest155_: '123-NEST-Haus-Konfigurator-155-Trapezblech-Schwarz-Ansicht',
        nest155_holzlattung: '122-NEST-Haus-Konfigurator-155-Holzfassade-Ansicht',
        nest155_plattenschwarz: '120-NEST-Haus-Konfigurator-155-Fassadenplatten-Schwarz-Ansicht',
        nest155_plattenweiss: '121-NEST-Haus-Konfigurator-155-Fassadenplatten-Weiss-Ansicht',
        nest155_trapezblech: '123-NEST-Haus-Konfigurator-155-Trapezblech-Schwarz-Ansicht',
        nest186_: '148-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Granit-IpwN186rpQc3H78Mw',
        nest198_: '162-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Granit-a5wwIs198nhkaKWKQ',
        nest22_: '142-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Granit-PGYpgCVlxqaUw22fQ',
        nest326_: '170-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Parkett-Eiche-jDUhrnvCHoicp326w',
        nest33_: '169-NEST-Haus-Konfigurator-Modul-Holzfassade-Holz-weiss-gekalkt-Kalkstein-JIXY33ahp8BOoqut5g',
        nest35_: '141-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Parkett-Eiche-IUYjf35xTMYEolGWYg',
        nest60_: '153-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Kalkstein-f1cdsmwjetTj60Npg',
        nest75: '104-NEST-Haus-Konfigurator-75-Holzfassade-Ansicht',
        nest75_: '107-NEST-Haus-Konfigurator-75-Trapezblech-Schwarz-Stirnseite',
        nest75_holzlattung: '104-NEST-Haus-Konfigurator-75-Holzfassade-Ansicht',
        nest75_plattenschwarz: '100-NEST-Haus-Konfigurator-75-Fassadenplatten-Schwarz-Ansicht',
        nest75_plattenweiss: '102-NEST-Haus-Konfigurator-75-Fassadenplatten-Weiss-Ansicht',
        nest75_trapezblech: '106-NEST-Haus-Konfigurator-75-Trapezblech-Schwarz-Ansicht',
        nest79_: '150-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Parkett-Eiche-8NSJz79JQMAnBa6w',
        nest83_: '156-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Kalkstein-hr83C1gzvhg9HQwNA',
        nest87_: '144-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Parkett-Eiche-z87iJz4h9hj1AcHNw',
        nest879_: '146-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Kalkstein-EW879zrtV7iYaBtrdw',
        nest89_: '160-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Parkett-Eiche-VnvD2N3cTaALy89mg',
        nest95: '110-NEST-Haus-Konfigurator-95-Holzfassade-Ansicht',
        nest95_: '111-NEST-Haus-Konfigurator-95-Trapezblech-Schwarz-Ansicht',
        nest95_holzlattung: '110-NEST-Haus-Konfigurator-95-Holzfassade-Ansicht',
        nest95_plattenschwarz: '108-NEST-Haus-Konfigurator-95-Fassadenplatten-Schwarz-Ansicht',
        nest95_plattenweiss: '109-NEST-Haus-Konfigurator-95-Fassadenplatten-Weiss-Ansicht',
        nest95_trapezblech: '111-NEST-Haus-Konfigurator-95-Trapezblech-Schwarz-Ansicht',
        plattenschwarz_eiche_granit: '152-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Granit',
        plattenschwarz_eiche_kalkstein: '153-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Kalkstein',
        plattenschwarz_eiche_parkett: '154-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Steirische-Eiche-Parkett-Eiche',
        plattenschwarz_holznatur_granit: '145-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Granit',
        plattenschwarz_holznatur_kalkstein: '146-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Kalkstein',
        plattenschwarz_holznatur_parkett: '147-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Parkett-Eiche',
        plattenschwarz_holzweiss_granit: '148-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Granit',
        plattenschwarz_holzweiss_kalkstein: '149-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Kalkstein',
        plattenschwarz_holzweiss_parkett: '150-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-weiss-gekalkt-Parkett-Eiche',
        plattenschwarz_interior: '145-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Holz-Natur-Granit',
        plattenweiss_eiche_granit: '162-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Granit',
        plattenweiss_eiche_kalkstein: '163-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Kalkstein',
        plattenweiss_eiche_parkett: '164-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Steirische-Eiche-Parkett-Eiche',
        plattenweiss_holznatur_granit: '155-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Granit',
        plattenweiss_holznatur_kalkstein: '156-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Kalkstein',
        plattenweiss_holznatur_parkett: '157-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Parkett-Eiche',
        plattenweiss_holzweiss_granit: '158-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Granit',
        plattenweiss_holzweiss_kalkstein: '159-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Kalkstein',
        plattenweiss_holzweiss_parkett: '160-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-weiss-gekalkt-Parkett-Eiche',
        plattenweiss_interior: '155-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Holz-Natur-Granit',
        pv_holzfassade: '134-NEST-Haus-Konfigurator-Modul-Fassade-Holzfassade-Photovoltaik-PV-Panel',
        pv_plattenschwarz: '151-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Schwarz-Photovoltaik-PV-Panel',
        pv_plattenweiss: '161-NEST-Haus-Konfigurator-Modul-Fassadenplatten-Weiss-Photovoltaik-PV-Panel',
        pv_trapezblech: '135-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Photovoltaik-PV-Panel',
        stirnseiteHolzfassade: '105-NEST-Haus-Konfigurator-75-Holzfassade-Stirnseite',
        stirnseitePlattenSchwarz: '101-NEST-Haus-Konfigurator-75-Fassadenplatten-Schwarz-Stirnseite',
        stirnseitePlattenWeiss: '103-NEST-Haus-Konfigurator-75-Fassadenplatten-Weiss-Stirnseite',
        stirnseiteTrapezblech: '107-NEST-Haus-Konfigurator-75-Trapezblech-Schwarz-Stirnseite',
        trapezblech_eiche_granit: '142-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Granit',
        trapezblech_eiche_kalkstein: '143-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Kalkstein',
        trapezblech_eiche_parkett: '144-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Steirische-Eiche-Parkett-Eiche',
        trapezblech_holznatur_granit: '136-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Granit',
        trapezblech_holznatur_kalkstein: '137-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Kalkstein',
        trapezblech_holznatur_parkett: '138-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Parkett-Eiche',
        trapezblech_holzweiss_granit: '139-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Granit',
        trapezblech_holzweiss_kalkstein: '140-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Kalkstein',
        trapezblech_holzweiss_parkett: '141-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Weiss-gekalkt-Parkett-Eiche',
        trapezblech_interior: '133-NEST-Haus-Konfigurator-Modul-Fassade-Trapezblech-Schwarz-Holz-Natur-Kalkstein'
        },

    // Material detail images for dialogs
    materials: {
        holzFichte: '58-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Interior-Fichte-natur-hell',
        schiefer: '57-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Schiefer-Feinsteinzeug',
        laercheFassade: '52-NEST-Haus-Materialien-Oberflaechen-Fassade-Laerche-Bauholz-Lattung',
        kalkstein: '56-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Kalkstein-Kanafar',
        fundermax: '53-NEST-Haus-Materialien-Oberflaechen-Fassadenplatte-Schwarz',
        eicheParkett: '49-NEST-Haus-Materialien-Oberflaechen-Fussboden-Eichenholz-Parkett-Fischgraetparkett-Eiche',
        trapezblech: '55-NEST-Haus-Materialien-Oberflaechen-Fassade-Trapezblech-Blech-Schwarz'
    },

    // Interior material images for innenverkleidung dialog
    interiorMaterials: {
        eiche: '50-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Eichenholz-Interior-Eiche',
        fichte: '58-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Interior-Fichte-natur-hell',
        kiefer: '59-NEST-Haus-Materialien-Oberflaechen-Innenausbau-Interior-Kiefer-natur'
    },

    // Window/Fenster detail images
    windows: {
        pvc: '177-NEST-Haus-Fenster-Kunststoff-PVC-Fenster-Weiss-Kunststofffenster-PVCFenster',
        fichte: '175-NEST-Haus-Fenster-Holz-Fichte-Holzfenster-Fichtenfenster',
        aluminium: '176-NEST-Haus-Fenster-Aluminium-Fenster-Aluminiumfenster-Metallfenster',
        eiche: '174-NEST-Haus-Fenster-Holz-Eiche-Holzfenster-Eichenfenster'
    },

    // Flooring/Fußboden detail images
    flooring: {
        schiefer: '57-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Schiefer-Feinsteinzeug',
        kalkstein: '56-NEST-Haus-Materialien-Oberflaechen-Fussboden-Naturstein-Kalkstein-Kanafar',
        eicheParkett: '49-NEST-Haus-Materialien-Oberflaechen-Fussboden-Eichenholz-Parkett-Fischgraetparkett-Eiche'
    },

    // Fallback images
    fallbacks: {
        exterior: '/api/placeholder/1200/800?style=nest&text=Loading...',
        interior: '/api/placeholder/1200/800?style=nest&text=Loading...',
        stirnseite: '/api/placeholder/1200/800?style=nest&text=Loading...',
        default: '/api/placeholder/1200/800?style=nest&text=Loading...'
    }
} as const;

// Helper function to get image path
export const getImagePath = (category: keyof typeof IMAGES, key: string): string => {
    const categoryObj = IMAGES[category] as Record<string, string>;
    return categoryObj[key] || IMAGES.fallbacks.default;
};

// Type definitions
export type ImageCategory = keyof typeof IMAGES;
export type HeroImageKey = keyof typeof IMAGES.hero;
export type ConfigurationImageKey = keyof typeof IMAGES.configurations; 